// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8suwD6tvVKNKgUM0qq2jS7NJrbDONNqY',
    appId: '1:734434735459:web:d2e4c133a335935b860f56',
    messagingSenderId: '734434735459',
    projectId: 'healthy-food-app-12d5f',
    authDomain: 'healthy-food-app-12d5f.firebaseapp.com',
    storageBucket: 'healthy-food-app-12d5f.firebasestorage.app',
    measurementId: 'G-GCX88J6DHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV6ggRtGGz5rjxjOT4-aJaGzurJdGVGCs',
    appId: '1:734434735459:android:5b75e40119022b2f860f56',
    messagingSenderId: '734434735459',
    projectId: 'healthy-food-app-12d5f',
    storageBucket: 'healthy-food-app-12d5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7yJPawo-xMI2KAPGkalc644mGvLz7yso',
    appId: '1:734434735459:ios:e0329e9a139e78c1860f56',
    messagingSenderId: '734434735459',
    projectId: 'healthy-food-app-12d5f',
    storageBucket: 'healthy-food-app-12d5f.firebasestorage.app',
    iosBundleId: 'com.example.appfoodh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7yJPawo-xMI2KAPGkalc644mGvLz7yso',
    appId: '1:734434735459:ios:e0329e9a139e78c1860f56',
    messagingSenderId: '734434735459',
    projectId: 'healthy-food-app-12d5f',
    storageBucket: 'healthy-food-app-12d5f.firebasestorage.app',
    iosBundleId: 'com.example.appfoodh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8suwD6tvVKNKgUM0qq2jS7NJrbDONNqY',
    appId: '1:734434735459:web:b369e0f541a8511c860f56',
    messagingSenderId: '734434735459',
    projectId: 'healthy-food-app-12d5f',
    authDomain: 'healthy-food-app-12d5f.firebaseapp.com',
    storageBucket: 'healthy-food-app-12d5f.firebasestorage.app',
    measurementId: 'G-T0TQXFNLHQ',
  );
}
